package repository

import (
	"context"

	"google.golang.org/genai"
)

type AIRepository interface {
	GetEmbedding(ctx context.Context, text string) ([]float32, error)
	SendMessage(ctx context.Context, contents []*genai.Content) (string, error)
}

type DBRepository interface {
	// SaveEmbedding save embedding data.
	//
	// The key is on format document_path::chunk_no
	// For example docs/what-is-mcp-a-simple-guide-i-wish-i-had-earlier.md::00001
	//
	// The doc is the []float32 which is the vector embeddings, that generated by google ai's embedding model
	SaveEmbedding(key string, doc []float32) error

	// Search
	Search(vectors []float32) (string, error)
}
