package repository

import (
	"context"
	"pikomonde/ask-my-docs/entity"

	"google.golang.org/genai"
)

type AIRepository interface {
	GetEmbedding(ctx context.Context, text string) ([]float32, error)
	SendMessage(ctx context.Context, contents []*genai.Content) (string, error)
}

type DBRepository interface {
	// SaveDoc save doc and embedding data.
	//
	// The key is on format document_path::chunk_no
	// For example docs/what-is-mcp-a-simple-guide-i-wish-i-had-earlier.md::00001
	//
	// The doc is the entity.Doc which contains the vector embeddings, that generated by google ai's embedding model
	SaveDoc(key string, doc entity.Doc) error

	// Search
	Search(vectors []float32) ([]entity.Doc, error)
}
